[package]
name = "rust-ffi-tour"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
snappy-sys ={ path = "snappy-sys"}

[workspace]
members = ["snappy-sys"]
